### ISSUE TITLE
Semestre 

### ISSUE THREAD

**Issue by xYogiPTxvsc** [Krecharles/Datz#21]
Because of covid-19 most of the Luxembourgish schools got the semestre system. But that option isn’t available in the app. Its an issue and a suggestion. Btw nice app, keep the good work;)

**Comment by Krecharles** [comment]
First off, thanks for the compliment. It really means a lot to me to have positive feedback :)

The idea to introduce semesters due to covid has been suggested to me several times. However I don't believe that it is a worth the effort because 
1) the way the app stores data does not allow to easily change such things (I fear breaking it by accident and everybody loses their grades) 
2) It is only temporary, so I would need to undo it next year (I assume next year will be normal again)
3) If one does not fill in anything in the 3 trimester, then the app behaves as if it has only 2 trimesters.

So I don't think I will add that option. Thanks for the suggestion though, every bit helps :)
